GCC=g++ -dynamiclib -I$(PREFIX)/include  -O3 -msse3 -mfpmath=sse -m64

TARGET=$(PREFIX)/lib/libLispEd3363.dylib
TARGET2=$(PREFIX)/lib/libLispCurve1174.dylib

all: $(TARGET) $(TARGET2)

$(TARGET): ed3363_intf.cpp ed3363_intf.h
	$(GCC) -o libLispEd3363.dylib \
		ed3363_intf.cpp
	mv libLispEd3363.dylib $(TARGET)

$(TARGET2): curve1174_intf.cpp curve1174_intf.h
	$(GCC) -o libLispCurve1174.dylib \
		curve1174_intf.cpp
	mv libLispCurve1174.dylib $(TARGET2)
