(defpackage :emotiq/cosi
  (:use
   :cl
   :alexandria)
  (:nicknames :cosi)
  (:import-from :actors
   :=bind
   :=values
   :=defun
   :=lambda
   :=funcall
   :=apply
   :pmapcar
   :smapc
   :spawn
   :current-actor
   :send
   :recv
   :retry-recv
   :become
   :par
   :do-nothing
   :make-actor
   :set-executive-pool
   :with-borrowed-mailbox
   :pr)
  (:import-from :node
                :current-node
                :*top-node*
                :*current-node*
                :*blockchain*     
                :*blocks* 
                :*mempool*        
                :*utxos*     
                :*leader*         
                :*tx-changes*     
                :*had-work-p*
                :*election-calls*
                :*beacon*
                :*local-epoch*)
                
  (:export
   :neighborcast
   :send
   :reply
   :node-dispatcher
   :*cosi-prepare-timeout*
   :*cosi-commit-timeout*
   :leader-exec
   :*default-data-file*
   :*default-key-file*
   :generate-tree
   :reconstruct-tree
   :init-sim
   :reset-nodes
   :forwarding
   :startup-elections
   :set-nodes
   :get-witness-list
   ))
