GCC=g++ -dynamiclib -I$(PREFIX)/include  -O3 -msse3 -mfpmath=sse -m64

TARGET=$(PREFIX)/lib/libLispEd3363.dylib

all: $(TARGET)

$(TARGET): ed3363_intf.cpp ed3363_intf.h
	$(GCC) -o libLispEd3363.dylib \
		ed3363_intf.cpp \
                -Wl,-L$(PREFIX)/lib,-rpath,$(PREFIX)/lib
	mv libLispEd3363.dylib $(TARGET)
